# Site settings
title:          Justin Goldstein
description:    "Minimal Jekyll theme for storytellers"
baseurl:        ""
url:            "https://jusgolds.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Justin Goldstein
  url:          https://jusgolds.github.io
  email:        jusgolds@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /blog/:year-:month-:day/:title/
paginate:       5
paginate_path: "/blog/page:num/"

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
